"""add last_modified

Revision ID: 1eff262a5875
Revises: 7573bdab7d63
Create Date: 2016-03-19 20:08:36.481013

"""

# revision identifiers, used by Alembic.
revision = '1eff262a5875'
down_revision = '7573bdab7d63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('last_modified', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'last_modified')
    ### end Alembic commands ###
